declare type CarbonThemeType =
  | '3024-night'
  | 'a11y-dark'
  | 'blackboard'
  | 'base16-dark'
  | 'base16-light'
  | 'cobalt'
  | 'dracula-pro'
  | 'duotone-dark'
  | 'hopscotch'
  | 'lucario'
  | 'material'
  | 'monokai'
  | 'night-owl'
  | 'nord'
  | 'oceanic-next'
  | 'one-light'
  | 'one-dark'
  | 'panda-syntax'
  | 'paraiso-dark'
  | 'seti'
  | 'shades-of-purple'
  | 'solarized dark'
  | 'solarized light'
  | 'synthwave-84'
  | 'twilight'
  | 'verminal'
  | 'vscode'
  | 'yeti'
  | 'zenburn';
declare type CarbonFontFamilyType =
  | 'Anonymous Pro'
  | 'Cascadia Code'
  | 'Droid Sans Mono'
  | 'Fantasque Sans Mono'
  | 'Fira Code'
  | 'Hack'
  | 'IBM Plex Mono'
  | 'Inconsolata'
  | 'JetBrains Mono'
  | 'Monoid'
  | 'Source Code Pro'
  | 'Space Mono'
  | 'Ubuntu Mono';
